#./test_histgram filelist_dir/tight_WGJets2.txt test_uncertainty_hist_v2 2018 muon mc signal WGJets medium
./test_histgram filelist_dir/tight_ST_s.txt test_uncertainty_hist_v2 2018 muon mc signal ST_s medium
./test_histgram filelist_dir/tight_ST_t.txt test_uncertainty_hist_v2 2018 muon mc signal ST_t medium
./test_histgram filelist_dir/tight_ST_tbar.txt test_uncertainty_hist_v2 2018 muon mc signal ST_tbar medium
./test_histgram filelist_dir/tight_ST_tW.txt test_uncertainty_hist_v2 2018 muon mc signal ST_tW medium
./test_histgram filelist_dir/tight_ST_tbarW.txt test_uncertainty_hist_v2 2018 muon mc signal ST_tbarW medium
./test_histgram filelist_dir/tight_TTG.txt test_uncertainty_hist_v2 2018 muon mc signal TTG medium
./test_histgram filelist_dir/tight_WGJJ2.txt test_uncertainty_hist_v2 2018 muon mc signal WGJJ medium
./test_histgram filelist_dir/tight_WW.txt test_uncertainty_hist_v2 2018 muon mc signal WW medium
./test_histgram filelist_dir/tight_WZ.txt test_uncertainty_hist_v2 2018 muon mc signal WZ medium
./test_histgram filelist_dir/tight_ZZ.txt test_uncertainty_hist_v2 2018 muon mc signal ZZ medium
./test_histgram filelist_dir/tight_ZG.txt test_uncertainty_hist_v2 2018 muon mc signal ZG medium
#./test_histgram filelist_dir/tight_WGJets2.txt test_uncertainty_hist_v2 2018 muon mc control WGJets medium
./test_histgram filelist_dir/tight_ST_s.txt test_uncertainty_hist_v2 2018 muon mc control ST_s medium
./test_histgram filelist_dir/tight_ST_t.txt test_uncertainty_hist_v2 2018 muon mc control ST_t medium
./test_histgram filelist_dir/tight_ST_tbar.txt test_uncertainty_hist_v2 2018 muon mc control ST_tbar medium
./test_histgram filelist_dir/tight_ST_tW.txt test_uncertainty_hist_v2 2018 muon mc control ST_tW medium
./test_histgram filelist_dir/tight_ST_tbarW.txt test_uncertainty_hist_v2 2018 muon mc control ST_tbarW medium
./test_histgram filelist_dir/tight_TTG.txt test_uncertainty_hist_v2 2018 muon mc control TTG medium
./test_histgram filelist_dir/tight_WGJJ2.txt test_uncertainty_hist_v2 2018 muon mc control WGJJ medium
./test_histgram filelist_dir/tight_WW.txt test_uncertainty_hist_v2 2018 muon mc control WW medium
./test_histgram filelist_dir/tight_WZ.txt test_uncertainty_hist_v2 2018 muon mc control WZ medium
./test_histgram filelist_dir/tight_ZZ.txt test_uncertainty_hist_v2 2018 muon mc control ZZ medium
./test_histgram filelist_dir/tight_ZG.txt test_uncertainty_hist_v2 2018 muon mc control ZG medium
./test_histgram filelist_dir/tight_muon.txt test_uncertainty_hist_v2 2018 muon fakephoton signal SingleMuon medium
./test_histgram filelist_dir/tight_muon.txt test_uncertainty_hist_v2 2018 muon fakephoton control SingleMuon medium
