./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal TTG medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal WGJets medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal WGJJ medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ST_s medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ST_t medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ST_tbar medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ST_tW medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ST_tbarW medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal WW medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal WZ medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ZZ medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc signal ZG medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control TTG medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control WGJets medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control WGJJ medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ST_s medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ST_t medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ST_tbar medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ST_tW medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ST_tbarW medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control WW medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control WZ medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ZZ medium
./calculate_uncertainty_unfold hist_dir2 uncer_unfold2 2018 mc control ZG medium
