./calculate_uncertainty hist_dir2 uncer2 2018 mc signal WGJets medium
#./calculate_uncertainty hist_dir2 uncer2 2018 mc signal WGJJ medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ST_s medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ST_t medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ST_tbar medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ST_tW medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ST_tbarW medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal WW medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal WZ medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ZZ medium
./calculate_uncertainty hist_dir2 uncer2 2018 mc signal ZG medium
