#electron
./unfold_histgram filelist_dir/tight_WGJets2.txt test_unfold_hist_v10 2018 electron mc signal WGJets medium
./unfold_histgram filelist_dir/tight_ST_s.txt test_unfold_hist_v10 2018 electron mc signal ST_s medium
./unfold_histgram filelist_dir/tight_ST_t.txt test_unfold_hist_v10 2018 electron mc signal ST_t medium
./unfold_histgram filelist_dir/tight_ST_tbar.txt test_unfold_hist_v10 2018 electron mc signal ST_tbar medium
./unfold_histgram filelist_dir/tight_ST_tW.txt test_unfold_hist_v10 2018 electron mc signal ST_tW medium
./unfold_histgram filelist_dir/tight_ST_tbarW.txt test_unfold_hist_v10 2018 electron mc signal ST_tbarW medium
./unfold_histgram filelist_dir/tight_TTG.txt test_unfold_hist_v10 2018 electron mc signal TTG medium
./unfold_histgram_gen filelist_dir/tight_WGJJ_gen.txt test_unfold_hist_v10 2018 electron mc signal WGJJ medium
./unfold_histgram filelist_dir/tight_WW.txt test_unfold_hist_v10 2018 electron mc signal WW medium
./unfold_histgram filelist_dir/tight_WZ.txt test_unfold_hist_v10 2018 electron mc signal WZ medium
./unfold_histgram filelist_dir/tight_ZZ.txt test_unfold_hist_v10 2018 electron mc signal ZZ medium
./unfold_histgram filelist_dir/tight_ZG.txt test_unfold_hist_v10 2018 electron mc signal ZG medium
./unfold_histgram filelist_dir/tight_WGJets2.txt test_unfold_hist_v10 2018 electron mc control WGJets medium
./unfold_histgram filelist_dir/tight_ST_s.txt test_unfold_hist_v10 2018 electron mc control ST_s medium
./unfold_histgram filelist_dir/tight_ST_t.txt test_unfold_hist_v10 2018 electron mc control ST_t medium
./unfold_histgram filelist_dir/tight_ST_tbar.txt test_unfold_hist_v10 2018 electron mc control ST_tbar medium
./unfold_histgram filelist_dir/tight_ST_tW.txt test_unfold_hist_v10 2018 electron mc control ST_tW medium
./unfold_histgram filelist_dir/tight_ST_tbarW.txt test_unfold_hist_v10 2018 electron mc control ST_tbarW medium
./unfold_histgram filelist_dir/tight_TTG.txt test_unfold_hist_v10 2018 electron mc control TTG medium
./unfold_histgram_gen filelist_dir/tight_WGJJ_gen.txt test_unfold_hist_v10 2018 electron mc control WGJJ medium
./unfold_histgram filelist_dir/tight_WW.txt test_unfold_hist_v10 2018 electron mc control WW medium
./unfold_histgram filelist_dir/tight_WZ.txt test_unfold_hist_v10 2018 electron mc control WZ medium
./unfold_histgram filelist_dir/tight_ZZ.txt test_unfold_hist_v10 2018 electron mc control ZZ medium
./unfold_histgram filelist_dir/tight_ZG.txt test_unfold_hist_v10 2018 electron mc control ZG medium
#muon
./unfold_histgram filelist_dir/tight_WGJets2.txt test_unfold_hist_v10 2018 muon mc signal WGJets medium
./unfold_histgram filelist_dir/tight_ST_s.txt test_unfold_hist_v10 2018 muon mc signal ST_s medium
./unfold_histgram filelist_dir/tight_ST_t.txt test_unfold_hist_v10 2018 muon mc signal ST_t medium
./unfold_histgram filelist_dir/tight_ST_tbar.txt test_unfold_hist_v10 2018 muon mc signal ST_tbar medium
./unfold_histgram filelist_dir/tight_ST_tW.txt test_unfold_hist_v10 2018 muon mc signal ST_tW medium
./unfold_histgram filelist_dir/tight_ST_tbarW.txt test_unfold_hist_v10 2018 muon mc signal ST_tbarW medium
./unfold_histgram filelist_dir/tight_TTG.txt test_unfold_hist_v10 2018 muon mc signal TTG medium
./unfold_histgram_gen filelist_dir/tight_WGJJ_gen.txt test_unfold_hist_v10 2018 muon mc signal WGJJ medium
./unfold_histgram filelist_dir/tight_WW.txt test_unfold_hist_v10 2018 muon mc signal WW medium
./unfold_histgram filelist_dir/tight_WZ.txt test_unfold_hist_v10 2018 muon mc signal WZ medium
./unfold_histgram filelist_dir/tight_ZZ.txt test_unfold_hist_v10 2018 muon mc signal ZZ medium
./unfold_histgram filelist_dir/tight_ZG.txt test_unfold_hist_v10 2018 muon mc signal ZG medium
./unfold_histgram filelist_dir/tight_WGJets2.txt test_unfold_hist_v10 2018 muon mc control WGJets medium
./unfold_histgram filelist_dir/tight_ST_s.txt test_unfold_hist_v10 2018 muon mc control ST_s medium
./unfold_histgram filelist_dir/tight_ST_t.txt test_unfold_hist_v10 2018 muon mc control ST_t medium
./unfold_histgram filelist_dir/tight_ST_tbar.txt test_unfold_hist_v10 2018 muon mc control ST_tbar medium
./unfold_histgram filelist_dir/tight_ST_tW.txt test_unfold_hist_v10 2018 muon mc control ST_tW medium
./unfold_histgram filelist_dir/tight_ST_tbarW.txt test_unfold_hist_v10 2018 muon mc control ST_tbarW medium
./unfold_histgram filelist_dir/tight_TTG.txt test_unfold_hist_v10 2018 muon mc control TTG medium
./unfold_histgram_gen filelist_dir/tight_WGJJ_gen.txt test_unfold_hist_v10 2018 muon mc control WGJJ medium
./unfold_histgram filelist_dir/tight_WW.txt test_unfold_hist_v10 2018 muon mc control WW medium
./unfold_histgram filelist_dir/tight_WZ.txt test_unfold_hist_v10 2018 muon mc control WZ medium
./unfold_histgram filelist_dir/tight_ZZ.txt test_unfold_hist_v10 2018 muon mc control ZZ medium
./unfold_histgram filelist_dir/tight_ZG.txt test_unfold_hist_v10 2018 muon mc control ZG medium
