./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 1
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 2
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 3
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 4
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 5
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 6
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 7
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 8
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 9
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 10
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 11
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 12
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 13
./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 muon mc wgaqgc medium 14
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 1
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 2
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 3
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 4
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 5
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 6
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 7
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 8
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 9
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 10
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 11
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 12
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 13
#./fit_ratio2 filelist_dir/tight_WGJJ_aqgc.txt test_fit3 2018 electron mc wgaqgc medium 14
